#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Item {
    AbilityShield,
    Abomasite,
    Absolite,
    AbsoliteZ,
    AbsorbBulb,
    AdamantCrystal,
    AdamantOrb,
    AdrenalineOrb,
    Aerodactylite,
    Aggronite,
    AguavBerry,
    AirBalloon,
    Alakazite,
    AloraichiumZ,
    Altarianite,
    Ampharosite,
    ApicotBerry,
    ArmorFossil,
    AspearBerry,
    AssaultVest,
    Audinite,
    AuspiciousArmor,
    BabiriBerry,
    Banettite,
    Barbaracite,
    Baxcalibrite,
    BeastBall,
    Beedrillite,
    BelueBerry,
    Berry,
    BerryJuice,
    BerrySweet,
    BerserkGene,
    BigNugget,
    BigRoot,
    BindingBand,
    BitterBerry,
    BlackBelt,
    BlackGlasses,
    BlackSludge,
    Blastoisinite,
    Blazikenite,
    BlueOrb,
    BlukBerry,
    BlunderPolicy,
    BoosterEnergy,
    BottleCap,
    BrightPowder,
    BugGem,
    BugMemory,
    BuginiumZ,
    BurnDrive,
    BurntBerry,
    Cameruptite,
    CellBattery,
    Chandelurite,
    Charcoal,
    CharizarditeX,
    CharizarditeY,
    ChartiBerry,
    CheriBerry,
    CherishBall,
    Chesnaughtite,
    ChestoBerry,
    ChilanBerry,
    ChillDrive,
    Chimechite,
    ChippedPot,
    ChoiceBand,
    ChoiceScarf,
    ChoiceSpecs,
    ChopleBerry,
    ClawFossil,
    ClearAmulet,
    Clefablite,
    CloverSweet,
    CobaBerry,
    ColburBerry,
    CornerstoneMask,
    CornnBerry,
    CoverFossil,
    CovertCloak,
    Crabominite,
    CrackedPot,
    Crucibellite,
    CustapBerry,
    DampRock,
    DarkGem,
    DarkMemory,
    DarkiniumZ,
    Darkranite,
    DawnStone,
    DecidiumZ,
    DeepSeaScale,
    DeepSeaTooth,
    Delphoxite,
    DestinyKnot,
    Diancite,
    DiveBall,
    DomeFossil,
    DouseDrive,
    DracoPlate,
    Dragalgite,
    DragonFang,
    DragonGem,
    DragonMemory,
    DragonScale,
    Dragoninite,
    DragoniumZ,
    Drampanite,
    DreadPlate,
    DreamBall,
    DubiousDisc,
    DurinBerry,
    DuskBall,
    DuskStone,
    EarthPlate,
    Eelektrossite,
    EeviumZ,
    EjectButton,
    EjectPack,
    Electirizer,
    ElectricGem,
    ElectricMemory,
    ElectricSeed,
    ElectriumZ,
    Emboarite,
    EnigmaBerry,
    Eviolite,
    Excadrite,
    ExpertBelt,
    FairiumZ,
    FairyFeather,
    FairyGem,
    FairyMemory,
    Falinksite,
    FastBall,
    Feraligite,
    FightingGem,
    FightingMemory,
    FightiniumZ,
    FigyBerry,
    FireGem,
    FireMemory,
    FireStone,
    FiriumZ,
    FistPlate,
    FlameOrb,
    FlamePlate,
    FloatStone,
    Floettite,
    FlowerSweet,
    FlyingGem,
    FlyingMemory,
    FlyiniumZ,
    FocusBand,
    FocusSash,
    FossilizedBird,
    FossilizedDino,
    FossilizedDrake,
    FossilizedFish,
    FriendBall,
    Froslassite,
    FullIncense,
    GalaricaCuff,
    GalaricaWreath,
    Galladite,
    GanlonBerry,
    Garchompite,
    GarchompiteZ,
    Gardevoirite,
    Gengarite,
    GhostGem,
    GhostMemory,
    GhostiumZ,
    Glalitite,
    Glimmoranite,
    GoldBerry,
    GoldBottleCap,
    Golisopite,
    Golurkite,
    GrassGem,
    GrassMemory,
    GrassiumZ,
    GrassySeed,
    GreatBall,
    Greninjite,
    GrepaBerry,
    GripClaw,
    GriseousCore,
    GriseousOrb,
    GroundGem,
    GroundMemory,
    GroundiumZ,
    Gyaradosite,
    HabanBerry,
    HardStone,
    Hawluchanite,
    HealBall,
    HearthflameMask,
    HeatRock,
    Heatranite,
    HeavyBall,
    HeavyDutyBoots,
    HelixFossil,
    Heracronite,
    HondewBerry,
    Houndoominite,
    IapapaBerry,
    IceBerry,
    IceGem,
    IceMemory,
    IceStone,
    IciclePlate,
    IciumZ,
    IcyRock,
    InciniumZ,
    InsectPlate,
    IronBall,
    IronPlate,
    JabocaBerry,
    JawFossil,
    Kangaskhanite,
    KasibBerry,
    KebiaBerry,
    KeeBerry,
    KelpsyBerry,
    KingsRock,
    KommoniumZ,
    LaggingTail,
    LansatBerry,
    Latiasite,
    Latiosite,
    LaxIncense,
    LeafStone,
    Leek,
    Leftovers,
    LeppaBerry,
    LevelBall,
    LiechiBerry,
    LifeOrb,
    LightBall,
    LightClay,
    LoadedDice,
    Lopunnite,
    LoveBall,
    LoveSweet,
    Lucarionite,
    LucarioniteZ,
    LuckyPunch,
    LumBerry,
    LuminousMoss,
    LunaliumZ,
    LureBall,
    LustrousGlobe,
    LustrousOrb,
    LuxuryBall,
    LycaniumZ,
    MachoBrace,
    Magearnite,
    Magmarizer,
    Magnet,
    MagoBerry,
    MagostBerry,
    Mail,
    Malamarite,
    MaliciousArmor,
    Manectite,
    MarangaBerry,
    MarshadiumZ,
    MasterBall,
    MasterpieceTeacup,
    Mawilite,
    MeadowPlate,
    Medichamite,
    Meganiumite,
    MentalHerb,
    Meowsticite,
    Metagrossite,
    MetalAlloy,
    MetalCoat,
    MetalPowder,
    Metronome,
    MewniumZ,
    MewtwoniteX,
    MewtwoniteY,
    MicleBerry,
    MimikiumZ,
    MindPlate,
    MintBerry,
    MiracleBerry,
    MiracleSeed,
    MirrorHerb,
    MistySeed,
    MoonBall,
    MoonStone,
    MuscleBand,
    MysteryBerry,
    MysticWater,
    NanabBerry,
    NestBall,
    NetBall,
    NeverMeltIce,
    NomelBerry,
    NormalGem,
    NormaliumZ,
    OccaBerry,
    OddIncense,
    OldAmber,
    OranBerry,
    OvalStone,
    PRZCureBerry,
    PSNCureBerry,
    PamtreBerry,
    ParkBall,
    PasshoBerry,
    PayapaBerry,
    PechaBerry,
    PersimBerry,
    PetayaBerry,
    Pidgeotite,
    PikaniumZ,
    PikashuniumZ,
    PinapBerry,
    PinkBow,
    Pinsirite,
    PixiePlate,
    PlumeFossil,
    PoisonBarb,
    PoisonGem,
    PoisonMemory,
    PoisoniumZ,
    PokeBall,
    PolkadotBow,
    PomegBerry,
    PowerAnklet,
    PowerBand,
    PowerBelt,
    PowerBracer,
    PowerHerb,
    PowerLens,
    PowerWeight,
    PremierBall,
    PrettyFeather,
    PrimariumZ,
    PrismScale,
    ProtectivePads,
    Protector,
    PsychicGem,
    PsychicMemory,
    PsychicSeed,
    PsychiumZ,
    PunchingGlove,
    Pyroarite,
    QualotBerry,
    QuickBall,
    QuickClaw,
    QuickPowder,
    RabutaBerry,
    RaichuniteX,
    RaichuniteY,
    RareBone,
    RawstBerry,
    RazorClaw,
    RazorFang,
    RazzBerry,
    ReaperCloth,
    RedCard,
    RedOrb,
    RepeatBall,
    RibbonSweet,
    RindoBerry,
    RingTarget,
    RockGem,
    RockIncense,
    RockMemory,
    RockiumZ,
    RockyHelmet,
    RoomService,
    RootFossil,
    RoseIncense,
    RoseliBerry,
    RowapBerry,
    RustedShield,
    RustedSword,
    Sablenite,
    Sachet,
    SafariBall,
    SafetyGoggles,
    SailFossil,
    SalacBerry,
    Salamencite,
    Sceptilite,
    Scizorite,
    Scolipite,
    ScopeLens,
    Scovillainite,
    Scraftinite,
    SeaIncense,
    SharpBeak,
    Sharpedonite,
    ShedShell,
    ShellBell,
    ShinyStone,
    ShockDrive,
    ShucaBerry,
    SilkScarf,
    SilverPowder,
    SitrusBerry,
    Skarmorite,
    SkullFossil,
    SkyPlate,
    Slowbronite,
    SmoothRock,
    SnorliumZ,
    Snowball,
    SoftSand,
    SolganiumZ,
    SoulDew,
    SpellTag,
    SpelonBerry,
    SplashPlate,
    SpookyPlate,
    SportBall,
    StarSweet,
    Staraptite,
    StarfBerry,
    Starminite,
    SteelGem,
    SteelMemory,
    SteeliumZ,
    Steelixite,
    Stick,
    StickyBarb,
    StonePlate,
    StrangeBall,
    StrawberrySweet,
    SunStone,
    Swampertite,
    SweetApple,
    SyrupyApple,
    TR00,
    TR01,
    TR02,
    TR03,
    TR04,
    TR05,
    TR06,
    TR07,
    TR08,
    TR09,
    TR10,
    TR11,
    TR12,
    TR13,
    TR14,
    TR15,
    TR16,
    TR17,
    TR18,
    TR19,
    TR20,
    TR21,
    TR22,
    TR23,
    TR24,
    TR25,
    TR26,
    TR27,
    TR28,
    TR29,
    TR30,
    TR31,
    TR32,
    TR33,
    TR34,
    TR35,
    TR36,
    TR37,
    TR38,
    TR39,
    TR40,
    TR41,
    TR42,
    TR43,
    TR44,
    TR45,
    TR46,
    TR47,
    TR48,
    TR49,
    TR50,
    TR51,
    TR52,
    TR53,
    TR54,
    TR55,
    TR56,
    TR57,
    TR58,
    TR59,
    TR60,
    TR61,
    TR62,
    TR63,
    TR64,
    TR65,
    TR66,
    TR67,
    TR68,
    TR69,
    TR70,
    TR71,
    TR72,
    TR73,
    TR74,
    TR75,
    TR76,
    TR77,
    TR78,
    TR79,
    TR80,
    TR81,
    TR82,
    TR83,
    TR84,
    TR85,
    TR86,
    TR87,
    TR88,
    TR89,
    TR90,
    TR91,
    TR92,
    TR93,
    TR94,
    TR95,
    TR96,
    TR97,
    TR98,
    TR99,
    TamatoBerry,
    TangaBerry,
    TapuniumZ,
    TartApple,
    Tatsugirinite,
    TerrainExtender,
    ThickClub,
    ThroatSpray,
    ThunderStone,
    TimerBall,
    ToxicOrb,
    ToxicPlate,
    TwistedSpoon,
    Tyranitarite,
    UltraBall,
    UltranecroziumZ,
    UnremarkableTeacup,
    UpGrade,
    UtilityUmbrella,
    Venusaurite,
    Victreebelite,
    VileVial,
    WacanBerry,
    WaterGem,
    WaterMemory,
    WaterStone,
    WateriumZ,
    WatmelBerry,
    WaveIncense,
    WeaknessPolicy,
    WellspringMask,
    WepearBerry,
    WhippedDream,
    WhiteHerb,
    WideLens,
    WikiBerry,
    WiseGlasses,
    YacheBerry,
    ZapPlate,
    Zeraorite,
    ZoomLens,
    Zygardite,
    None,
    Unknown(String),
}

impl Item {
    pub fn from_str(s: &str) -> Self {
        let normalize = |s: &str| s.chars().filter(|c| c.is_alphanumeric()).map(|c| c.to_ascii_lowercase()).collect::<String>();
        let normalized = normalize(s);
        match normalized.as_str() {
            "abilityshield" => Item::AbilityShield,
            "abomasite" => Item::Abomasite,
            "absolite" => Item::Absolite,
            "absolitez" => Item::AbsoliteZ,
            "absorbbulb" => Item::AbsorbBulb,
            "adamantcrystal" => Item::AdamantCrystal,
            "adamantorb" => Item::AdamantOrb,
            "adrenalineorb" => Item::AdrenalineOrb,
            "aerodactylite" => Item::Aerodactylite,
            "aggronite" => Item::Aggronite,
            "aguavberry" => Item::AguavBerry,
            "airballoon" => Item::AirBalloon,
            "alakazite" => Item::Alakazite,
            "aloraichiumz" => Item::AloraichiumZ,
            "altarianite" => Item::Altarianite,
            "ampharosite" => Item::Ampharosite,
            "apicotberry" => Item::ApicotBerry,
            "armorfossil" => Item::ArmorFossil,
            "aspearberry" => Item::AspearBerry,
            "assaultvest" => Item::AssaultVest,
            "audinite" => Item::Audinite,
            "auspiciousarmor" => Item::AuspiciousArmor,
            "babiriberry" => Item::BabiriBerry,
            "banettite" => Item::Banettite,
            "barbaracite" => Item::Barbaracite,
            "baxcalibrite" => Item::Baxcalibrite,
            "beastball" => Item::BeastBall,
            "beedrillite" => Item::Beedrillite,
            "belueberry" => Item::BelueBerry,
            "berry" => Item::Berry,
            "berryjuice" => Item::BerryJuice,
            "berrysweet" => Item::BerrySweet,
            "berserkgene" => Item::BerserkGene,
            "bignugget" => Item::BigNugget,
            "bigroot" => Item::BigRoot,
            "bindingband" => Item::BindingBand,
            "bitterberry" => Item::BitterBerry,
            "blackbelt" => Item::BlackBelt,
            "blackglasses" => Item::BlackGlasses,
            "blacksludge" => Item::BlackSludge,
            "blastoisinite" => Item::Blastoisinite,
            "blazikenite" => Item::Blazikenite,
            "blueorb" => Item::BlueOrb,
            "blukberry" => Item::BlukBerry,
            "blunderpolicy" => Item::BlunderPolicy,
            "boosterenergy" => Item::BoosterEnergy,
            "bottlecap" => Item::BottleCap,
            "brightpowder" => Item::BrightPowder,
            "buggem" => Item::BugGem,
            "bugmemory" => Item::BugMemory,
            "buginiumz" => Item::BuginiumZ,
            "burndrive" => Item::BurnDrive,
            "burntberry" => Item::BurntBerry,
            "cameruptite" => Item::Cameruptite,
            "cellbattery" => Item::CellBattery,
            "chandelurite" => Item::Chandelurite,
            "charcoal" => Item::Charcoal,
            "charizarditex" => Item::CharizarditeX,
            "charizarditey" => Item::CharizarditeY,
            "chartiberry" => Item::ChartiBerry,
            "cheriberry" => Item::CheriBerry,
            "cherishball" => Item::CherishBall,
            "chesnaughtite" => Item::Chesnaughtite,
            "chestoberry" => Item::ChestoBerry,
            "chilanberry" => Item::ChilanBerry,
            "chilldrive" => Item::ChillDrive,
            "chimechite" => Item::Chimechite,
            "chippedpot" => Item::ChippedPot,
            "choiceband" => Item::ChoiceBand,
            "choicescarf" => Item::ChoiceScarf,
            "choicespecs" => Item::ChoiceSpecs,
            "chopleberry" => Item::ChopleBerry,
            "clawfossil" => Item::ClawFossil,
            "clearamulet" => Item::ClearAmulet,
            "clefablite" => Item::Clefablite,
            "cloversweet" => Item::CloverSweet,
            "cobaberry" => Item::CobaBerry,
            "colburberry" => Item::ColburBerry,
            "cornerstonemask" => Item::CornerstoneMask,
            "cornnberry" => Item::CornnBerry,
            "coverfossil" => Item::CoverFossil,
            "covertcloak" => Item::CovertCloak,
            "crabominite" => Item::Crabominite,
            "crackedpot" => Item::CrackedPot,
            "crucibellite" => Item::Crucibellite,
            "custapberry" => Item::CustapBerry,
            "damprock" => Item::DampRock,
            "darkgem" => Item::DarkGem,
            "darkmemory" => Item::DarkMemory,
            "darkiniumz" => Item::DarkiniumZ,
            "darkranite" => Item::Darkranite,
            "dawnstone" => Item::DawnStone,
            "decidiumz" => Item::DecidiumZ,
            "deepseascale" => Item::DeepSeaScale,
            "deepseatooth" => Item::DeepSeaTooth,
            "delphoxite" => Item::Delphoxite,
            "destinyknot" => Item::DestinyKnot,
            "diancite" => Item::Diancite,
            "diveball" => Item::DiveBall,
            "domefossil" => Item::DomeFossil,
            "dousedrive" => Item::DouseDrive,
            "dracoplate" => Item::DracoPlate,
            "dragalgite" => Item::Dragalgite,
            "dragonfang" => Item::DragonFang,
            "dragongem" => Item::DragonGem,
            "dragonmemory" => Item::DragonMemory,
            "dragonscale" => Item::DragonScale,
            "dragoninite" => Item::Dragoninite,
            "dragoniumz" => Item::DragoniumZ,
            "drampanite" => Item::Drampanite,
            "dreadplate" => Item::DreadPlate,
            "dreamball" => Item::DreamBall,
            "dubiousdisc" => Item::DubiousDisc,
            "durinberry" => Item::DurinBerry,
            "duskball" => Item::DuskBall,
            "duskstone" => Item::DuskStone,
            "earthplate" => Item::EarthPlate,
            "eelektrossite" => Item::Eelektrossite,
            "eeviumz" => Item::EeviumZ,
            "ejectbutton" => Item::EjectButton,
            "ejectpack" => Item::EjectPack,
            "electirizer" => Item::Electirizer,
            "electricgem" => Item::ElectricGem,
            "electricmemory" => Item::ElectricMemory,
            "electricseed" => Item::ElectricSeed,
            "electriumz" => Item::ElectriumZ,
            "emboarite" => Item::Emboarite,
            "enigmaberry" => Item::EnigmaBerry,
            "eviolite" => Item::Eviolite,
            "excadrite" => Item::Excadrite,
            "expertbelt" => Item::ExpertBelt,
            "fairiumz" => Item::FairiumZ,
            "fairyfeather" => Item::FairyFeather,
            "fairygem" => Item::FairyGem,
            "fairymemory" => Item::FairyMemory,
            "falinksite" => Item::Falinksite,
            "fastball" => Item::FastBall,
            "feraligite" => Item::Feraligite,
            "fightinggem" => Item::FightingGem,
            "fightingmemory" => Item::FightingMemory,
            "fightiniumz" => Item::FightiniumZ,
            "figyberry" => Item::FigyBerry,
            "firegem" => Item::FireGem,
            "firememory" => Item::FireMemory,
            "firestone" => Item::FireStone,
            "firiumz" => Item::FiriumZ,
            "fistplate" => Item::FistPlate,
            "flameorb" => Item::FlameOrb,
            "flameplate" => Item::FlamePlate,
            "floatstone" => Item::FloatStone,
            "floettite" => Item::Floettite,
            "flowersweet" => Item::FlowerSweet,
            "flyinggem" => Item::FlyingGem,
            "flyingmemory" => Item::FlyingMemory,
            "flyiniumz" => Item::FlyiniumZ,
            "focusband" => Item::FocusBand,
            "focussash" => Item::FocusSash,
            "fossilizedbird" => Item::FossilizedBird,
            "fossilizeddino" => Item::FossilizedDino,
            "fossilizeddrake" => Item::FossilizedDrake,
            "fossilizedfish" => Item::FossilizedFish,
            "friendball" => Item::FriendBall,
            "froslassite" => Item::Froslassite,
            "fullincense" => Item::FullIncense,
            "galaricacuff" => Item::GalaricaCuff,
            "galaricawreath" => Item::GalaricaWreath,
            "galladite" => Item::Galladite,
            "ganlonberry" => Item::GanlonBerry,
            "garchompite" => Item::Garchompite,
            "garchompitez" => Item::GarchompiteZ,
            "gardevoirite" => Item::Gardevoirite,
            "gengarite" => Item::Gengarite,
            "ghostgem" => Item::GhostGem,
            "ghostmemory" => Item::GhostMemory,
            "ghostiumz" => Item::GhostiumZ,
            "glalitite" => Item::Glalitite,
            "glimmoranite" => Item::Glimmoranite,
            "goldberry" => Item::GoldBerry,
            "goldbottlecap" => Item::GoldBottleCap,
            "golisopite" => Item::Golisopite,
            "golurkite" => Item::Golurkite,
            "grassgem" => Item::GrassGem,
            "grassmemory" => Item::GrassMemory,
            "grassiumz" => Item::GrassiumZ,
            "grassyseed" => Item::GrassySeed,
            "greatball" => Item::GreatBall,
            "greninjite" => Item::Greninjite,
            "grepaberry" => Item::GrepaBerry,
            "gripclaw" => Item::GripClaw,
            "griseouscore" => Item::GriseousCore,
            "griseousorb" => Item::GriseousOrb,
            "groundgem" => Item::GroundGem,
            "groundmemory" => Item::GroundMemory,
            "groundiumz" => Item::GroundiumZ,
            "gyaradosite" => Item::Gyaradosite,
            "habanberry" => Item::HabanBerry,
            "hardstone" => Item::HardStone,
            "hawluchanite" => Item::Hawluchanite,
            "healball" => Item::HealBall,
            "hearthflamemask" => Item::HearthflameMask,
            "heatrock" => Item::HeatRock,
            "heatranite" => Item::Heatranite,
            "heavyball" => Item::HeavyBall,
            "heavydutyboots" => Item::HeavyDutyBoots,
            "helixfossil" => Item::HelixFossil,
            "heracronite" => Item::Heracronite,
            "hondewberry" => Item::HondewBerry,
            "houndoominite" => Item::Houndoominite,
            "iapapaberry" => Item::IapapaBerry,
            "iceberry" => Item::IceBerry,
            "icegem" => Item::IceGem,
            "icememory" => Item::IceMemory,
            "icestone" => Item::IceStone,
            "icicleplate" => Item::IciclePlate,
            "iciumz" => Item::IciumZ,
            "icyrock" => Item::IcyRock,
            "inciniumz" => Item::InciniumZ,
            "insectplate" => Item::InsectPlate,
            "ironball" => Item::IronBall,
            "ironplate" => Item::IronPlate,
            "jabocaberry" => Item::JabocaBerry,
            "jawfossil" => Item::JawFossil,
            "kangaskhanite" => Item::Kangaskhanite,
            "kasibberry" => Item::KasibBerry,
            "kebiaberry" => Item::KebiaBerry,
            "keeberry" => Item::KeeBerry,
            "kelpsyberry" => Item::KelpsyBerry,
            "kingsrock" => Item::KingsRock,
            "kommoniumz" => Item::KommoniumZ,
            "laggingtail" => Item::LaggingTail,
            "lansatberry" => Item::LansatBerry,
            "latiasite" => Item::Latiasite,
            "latiosite" => Item::Latiosite,
            "laxincense" => Item::LaxIncense,
            "leafstone" => Item::LeafStone,
            "leek" => Item::Leek,
            "leftovers" => Item::Leftovers,
            "leppaberry" => Item::LeppaBerry,
            "levelball" => Item::LevelBall,
            "liechiberry" => Item::LiechiBerry,
            "lifeorb" => Item::LifeOrb,
            "lightball" => Item::LightBall,
            "lightclay" => Item::LightClay,
            "loadeddice" => Item::LoadedDice,
            "lopunnite" => Item::Lopunnite,
            "loveball" => Item::LoveBall,
            "lovesweet" => Item::LoveSweet,
            "lucarionite" => Item::Lucarionite,
            "lucarionitez" => Item::LucarioniteZ,
            "luckypunch" => Item::LuckyPunch,
            "lumberry" => Item::LumBerry,
            "luminousmoss" => Item::LuminousMoss,
            "lunaliumz" => Item::LunaliumZ,
            "lureball" => Item::LureBall,
            "lustrousglobe" => Item::LustrousGlobe,
            "lustrousorb" => Item::LustrousOrb,
            "luxuryball" => Item::LuxuryBall,
            "lycaniumz" => Item::LycaniumZ,
            "machobrace" => Item::MachoBrace,
            "magearnite" => Item::Magearnite,
            "magmarizer" => Item::Magmarizer,
            "magnet" => Item::Magnet,
            "magoberry" => Item::MagoBerry,
            "magostberry" => Item::MagostBerry,
            "mail" => Item::Mail,
            "malamarite" => Item::Malamarite,
            "maliciousarmor" => Item::MaliciousArmor,
            "manectite" => Item::Manectite,
            "marangaberry" => Item::MarangaBerry,
            "marshadiumz" => Item::MarshadiumZ,
            "masterball" => Item::MasterBall,
            "masterpieceteacup" => Item::MasterpieceTeacup,
            "mawilite" => Item::Mawilite,
            "meadowplate" => Item::MeadowPlate,
            "medichamite" => Item::Medichamite,
            "meganiumite" => Item::Meganiumite,
            "mentalherb" => Item::MentalHerb,
            "meowsticite" => Item::Meowsticite,
            "metagrossite" => Item::Metagrossite,
            "metalalloy" => Item::MetalAlloy,
            "metalcoat" => Item::MetalCoat,
            "metalpowder" => Item::MetalPowder,
            "metronome" => Item::Metronome,
            "mewniumz" => Item::MewniumZ,
            "mewtwonitex" => Item::MewtwoniteX,
            "mewtwonitey" => Item::MewtwoniteY,
            "micleberry" => Item::MicleBerry,
            "mimikiumz" => Item::MimikiumZ,
            "mindplate" => Item::MindPlate,
            "mintberry" => Item::MintBerry,
            "miracleberry" => Item::MiracleBerry,
            "miracleseed" => Item::MiracleSeed,
            "mirrorherb" => Item::MirrorHerb,
            "mistyseed" => Item::MistySeed,
            "moonball" => Item::MoonBall,
            "moonstone" => Item::MoonStone,
            "muscleband" => Item::MuscleBand,
            "mysteryberry" => Item::MysteryBerry,
            "mysticwater" => Item::MysticWater,
            "nanabberry" => Item::NanabBerry,
            "nestball" => Item::NestBall,
            "netball" => Item::NetBall,
            "nevermeltice" => Item::NeverMeltIce,
            "nomelberry" => Item::NomelBerry,
            "normalgem" => Item::NormalGem,
            "normaliumz" => Item::NormaliumZ,
            "occaberry" => Item::OccaBerry,
            "oddincense" => Item::OddIncense,
            "oldamber" => Item::OldAmber,
            "oranberry" => Item::OranBerry,
            "ovalstone" => Item::OvalStone,
            "przcureberry" => Item::PRZCureBerry,
            "psncureberry" => Item::PSNCureBerry,
            "pamtreberry" => Item::PamtreBerry,
            "parkball" => Item::ParkBall,
            "passhoberry" => Item::PasshoBerry,
            "payapaberry" => Item::PayapaBerry,
            "pechaberry" => Item::PechaBerry,
            "persimberry" => Item::PersimBerry,
            "petayaberry" => Item::PetayaBerry,
            "pidgeotite" => Item::Pidgeotite,
            "pikaniumz" => Item::PikaniumZ,
            "pikashuniumz" => Item::PikashuniumZ,
            "pinapberry" => Item::PinapBerry,
            "pinkbow" => Item::PinkBow,
            "pinsirite" => Item::Pinsirite,
            "pixieplate" => Item::PixiePlate,
            "plumefossil" => Item::PlumeFossil,
            "poisonbarb" => Item::PoisonBarb,
            "poisongem" => Item::PoisonGem,
            "poisonmemory" => Item::PoisonMemory,
            "poisoniumz" => Item::PoisoniumZ,
            "pokeball" => Item::PokeBall,
            "polkadotbow" => Item::PolkadotBow,
            "pomegberry" => Item::PomegBerry,
            "poweranklet" => Item::PowerAnklet,
            "powerband" => Item::PowerBand,
            "powerbelt" => Item::PowerBelt,
            "powerbracer" => Item::PowerBracer,
            "powerherb" => Item::PowerHerb,
            "powerlens" => Item::PowerLens,
            "powerweight" => Item::PowerWeight,
            "premierball" => Item::PremierBall,
            "prettyfeather" => Item::PrettyFeather,
            "primariumz" => Item::PrimariumZ,
            "prismscale" => Item::PrismScale,
            "protectivepads" => Item::ProtectivePads,
            "protector" => Item::Protector,
            "psychicgem" => Item::PsychicGem,
            "psychicmemory" => Item::PsychicMemory,
            "psychicseed" => Item::PsychicSeed,
            "psychiumz" => Item::PsychiumZ,
            "punchingglove" => Item::PunchingGlove,
            "pyroarite" => Item::Pyroarite,
            "qualotberry" => Item::QualotBerry,
            "quickball" => Item::QuickBall,
            "quickclaw" => Item::QuickClaw,
            "quickpowder" => Item::QuickPowder,
            "rabutaberry" => Item::RabutaBerry,
            "raichunitex" => Item::RaichuniteX,
            "raichunitey" => Item::RaichuniteY,
            "rarebone" => Item::RareBone,
            "rawstberry" => Item::RawstBerry,
            "razorclaw" => Item::RazorClaw,
            "razorfang" => Item::RazorFang,
            "razzberry" => Item::RazzBerry,
            "reapercloth" => Item::ReaperCloth,
            "redcard" => Item::RedCard,
            "redorb" => Item::RedOrb,
            "repeatball" => Item::RepeatBall,
            "ribbonsweet" => Item::RibbonSweet,
            "rindoberry" => Item::RindoBerry,
            "ringtarget" => Item::RingTarget,
            "rockgem" => Item::RockGem,
            "rockincense" => Item::RockIncense,
            "rockmemory" => Item::RockMemory,
            "rockiumz" => Item::RockiumZ,
            "rockyhelmet" => Item::RockyHelmet,
            "roomservice" => Item::RoomService,
            "rootfossil" => Item::RootFossil,
            "roseincense" => Item::RoseIncense,
            "roseliberry" => Item::RoseliBerry,
            "rowapberry" => Item::RowapBerry,
            "rustedshield" => Item::RustedShield,
            "rustedsword" => Item::RustedSword,
            "sablenite" => Item::Sablenite,
            "sachet" => Item::Sachet,
            "safariball" => Item::SafariBall,
            "safetygoggles" => Item::SafetyGoggles,
            "sailfossil" => Item::SailFossil,
            "salacberry" => Item::SalacBerry,
            "salamencite" => Item::Salamencite,
            "sceptilite" => Item::Sceptilite,
            "scizorite" => Item::Scizorite,
            "scolipite" => Item::Scolipite,
            "scopelens" => Item::ScopeLens,
            "scovillainite" => Item::Scovillainite,
            "scraftinite" => Item::Scraftinite,
            "seaincense" => Item::SeaIncense,
            "sharpbeak" => Item::SharpBeak,
            "sharpedonite" => Item::Sharpedonite,
            "shedshell" => Item::ShedShell,
            "shellbell" => Item::ShellBell,
            "shinystone" => Item::ShinyStone,
            "shockdrive" => Item::ShockDrive,
            "shucaberry" => Item::ShucaBerry,
            "silkscarf" => Item::SilkScarf,
            "silverpowder" => Item::SilverPowder,
            "sitrusberry" => Item::SitrusBerry,
            "skarmorite" => Item::Skarmorite,
            "skullfossil" => Item::SkullFossil,
            "skyplate" => Item::SkyPlate,
            "slowbronite" => Item::Slowbronite,
            "smoothrock" => Item::SmoothRock,
            "snorliumz" => Item::SnorliumZ,
            "snowball" => Item::Snowball,
            "softsand" => Item::SoftSand,
            "solganiumz" => Item::SolganiumZ,
            "souldew" => Item::SoulDew,
            "spelltag" => Item::SpellTag,
            "spelonberry" => Item::SpelonBerry,
            "splashplate" => Item::SplashPlate,
            "spookyplate" => Item::SpookyPlate,
            "sportball" => Item::SportBall,
            "starsweet" => Item::StarSweet,
            "staraptite" => Item::Staraptite,
            "starfberry" => Item::StarfBerry,
            "starminite" => Item::Starminite,
            "steelgem" => Item::SteelGem,
            "steelmemory" => Item::SteelMemory,
            "steeliumz" => Item::SteeliumZ,
            "steelixite" => Item::Steelixite,
            "stick" => Item::Stick,
            "stickybarb" => Item::StickyBarb,
            "stoneplate" => Item::StonePlate,
            "strangeball" => Item::StrangeBall,
            "strawberrysweet" => Item::StrawberrySweet,
            "sunstone" => Item::SunStone,
            "swampertite" => Item::Swampertite,
            "sweetapple" => Item::SweetApple,
            "syrupyapple" => Item::SyrupyApple,
            "tr00" => Item::TR00,
            "tr01" => Item::TR01,
            "tr02" => Item::TR02,
            "tr03" => Item::TR03,
            "tr04" => Item::TR04,
            "tr05" => Item::TR05,
            "tr06" => Item::TR06,
            "tr07" => Item::TR07,
            "tr08" => Item::TR08,
            "tr09" => Item::TR09,
            "tr10" => Item::TR10,
            "tr11" => Item::TR11,
            "tr12" => Item::TR12,
            "tr13" => Item::TR13,
            "tr14" => Item::TR14,
            "tr15" => Item::TR15,
            "tr16" => Item::TR16,
            "tr17" => Item::TR17,
            "tr18" => Item::TR18,
            "tr19" => Item::TR19,
            "tr20" => Item::TR20,
            "tr21" => Item::TR21,
            "tr22" => Item::TR22,
            "tr23" => Item::TR23,
            "tr24" => Item::TR24,
            "tr25" => Item::TR25,
            "tr26" => Item::TR26,
            "tr27" => Item::TR27,
            "tr28" => Item::TR28,
            "tr29" => Item::TR29,
            "tr30" => Item::TR30,
            "tr31" => Item::TR31,
            "tr32" => Item::TR32,
            "tr33" => Item::TR33,
            "tr34" => Item::TR34,
            "tr35" => Item::TR35,
            "tr36" => Item::TR36,
            "tr37" => Item::TR37,
            "tr38" => Item::TR38,
            "tr39" => Item::TR39,
            "tr40" => Item::TR40,
            "tr41" => Item::TR41,
            "tr42" => Item::TR42,
            "tr43" => Item::TR43,
            "tr44" => Item::TR44,
            "tr45" => Item::TR45,
            "tr46" => Item::TR46,
            "tr47" => Item::TR47,
            "tr48" => Item::TR48,
            "tr49" => Item::TR49,
            "tr50" => Item::TR50,
            "tr51" => Item::TR51,
            "tr52" => Item::TR52,
            "tr53" => Item::TR53,
            "tr54" => Item::TR54,
            "tr55" => Item::TR55,
            "tr56" => Item::TR56,
            "tr57" => Item::TR57,
            "tr58" => Item::TR58,
            "tr59" => Item::TR59,
            "tr60" => Item::TR60,
            "tr61" => Item::TR61,
            "tr62" => Item::TR62,
            "tr63" => Item::TR63,
            "tr64" => Item::TR64,
            "tr65" => Item::TR65,
            "tr66" => Item::TR66,
            "tr67" => Item::TR67,
            "tr68" => Item::TR68,
            "tr69" => Item::TR69,
            "tr70" => Item::TR70,
            "tr71" => Item::TR71,
            "tr72" => Item::TR72,
            "tr73" => Item::TR73,
            "tr74" => Item::TR74,
            "tr75" => Item::TR75,
            "tr76" => Item::TR76,
            "tr77" => Item::TR77,
            "tr78" => Item::TR78,
            "tr79" => Item::TR79,
            "tr80" => Item::TR80,
            "tr81" => Item::TR81,
            "tr82" => Item::TR82,
            "tr83" => Item::TR83,
            "tr84" => Item::TR84,
            "tr85" => Item::TR85,
            "tr86" => Item::TR86,
            "tr87" => Item::TR87,
            "tr88" => Item::TR88,
            "tr89" => Item::TR89,
            "tr90" => Item::TR90,
            "tr91" => Item::TR91,
            "tr92" => Item::TR92,
            "tr93" => Item::TR93,
            "tr94" => Item::TR94,
            "tr95" => Item::TR95,
            "tr96" => Item::TR96,
            "tr97" => Item::TR97,
            "tr98" => Item::TR98,
            "tr99" => Item::TR99,
            "tamatoberry" => Item::TamatoBerry,
            "tangaberry" => Item::TangaBerry,
            "tapuniumz" => Item::TapuniumZ,
            "tartapple" => Item::TartApple,
            "tatsugirinite" => Item::Tatsugirinite,
            "terrainextender" => Item::TerrainExtender,
            "thickclub" => Item::ThickClub,
            "throatspray" => Item::ThroatSpray,
            "thunderstone" => Item::ThunderStone,
            "timerball" => Item::TimerBall,
            "toxicorb" => Item::ToxicOrb,
            "toxicplate" => Item::ToxicPlate,
            "twistedspoon" => Item::TwistedSpoon,
            "tyranitarite" => Item::Tyranitarite,
            "ultraball" => Item::UltraBall,
            "ultranecroziumz" => Item::UltranecroziumZ,
            "unremarkableteacup" => Item::UnremarkableTeacup,
            "upgrade" => Item::UpGrade,
            "utilityumbrella" => Item::UtilityUmbrella,
            "venusaurite" => Item::Venusaurite,
            "victreebelite" => Item::Victreebelite,
            "vilevial" => Item::VileVial,
            "wacanberry" => Item::WacanBerry,
            "watergem" => Item::WaterGem,
            "watermemory" => Item::WaterMemory,
            "waterstone" => Item::WaterStone,
            "wateriumz" => Item::WateriumZ,
            "watmelberry" => Item::WatmelBerry,
            "waveincense" => Item::WaveIncense,
            "weaknesspolicy" => Item::WeaknessPolicy,
            "wellspringmask" => Item::WellspringMask,
            "wepearberry" => Item::WepearBerry,
            "whippeddream" => Item::WhippedDream,
            "whiteherb" => Item::WhiteHerb,
            "widelens" => Item::WideLens,
            "wikiberry" => Item::WikiBerry,
            "wiseglasses" => Item::WiseGlasses,
            "yacheberry" => Item::YacheBerry,
            "zapplate" => Item::ZapPlate,
            "zeraorite" => Item::Zeraorite,
            "zoomlens" => Item::ZoomLens,
            "zygardite" => Item::Zygardite,
            "" => Item::None,
            "none" => Item::None,
            _ => Item::Unknown(s.to_string()),
        }
    }
}
